name: Build, Lint, and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-lint-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile --ignore-scripts
      - run: yarn allow-scripts
      - run: yarn build
      - run: yarn lint
      # We have to use xvfb due to electron
      # Ref: https://github.com/facebook-atom/jest-electron-runner/issues/47#issuecomment-508556407
      - run: xvfb-run -e /dev/stdout yarn test
  all-jobs-pass:
    name: All jobs pass
    runs-on: ubuntu-20.04
    needs:
      - build-lint-test
    steps:
      - uses: actions/checkout@v2
      - run: echo "Great success!"
