name: Build, Lint, and Test

on:
  workflow_call:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install Corepack via Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install Yarn
        run: corepack enable
      - name: Install Node.js ${{ matrix.node-version }} and restore Yarn cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      # TODO: Remove --ignore-engines once devdeps compatible with node v20
      - name: Install dependencies via Yarn (ignoring engines)
        run: yarn --frozen-lockfile --ignore-engines
        if: "startsWith(matrix.node-version, '2')"
      - name: Install dependencies via Yarn
        run: yarn --frozen-lockfile
        if: "!startsWith(matrix.node-version, '2')"

  build:
    name: Build
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install Corepack via Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install Yarn
        run: corepack enable
      - name: Install Node.js ${{ matrix.node-version }} and restore Yarn cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      # TODO: Remove --ignore-engines once devdeps compatible with node v20
      - name: Install dependencies via Yarn (ignoring engines)
        run: yarn --frozen-lockfile --ignore-engines
        if: "startsWith(matrix.node-version, '2')"
      - name: Install dependencies via Yarn
        run: yarn --frozen-lockfile
        if: "!startsWith(matrix.node-version, '2')"
      - run: yarn build
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi

  lint:
    name: Lint
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install Corepack via Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install Yarn
        run: corepack enable
      - name: Install Node.js ${{ matrix.node-version }} and restore Yarn cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      # TODO: Remove --ignore-engines once devdeps compatible with node v20
      - name: Install dependencies via Yarn (ignoring engines)
        run: yarn --frozen-lockfile --ignore-engines
        if: "startsWith(matrix.node-version, '2')"
      - name: Install dependencies via Yarn
        run: yarn --frozen-lockfile
        if: "!startsWith(matrix.node-version, '2')"
      - run: yarn lint
      - name: Validate RC changelog
        if: ${{ startsWith(github.head_ref, 'release/') }}
        run: yarn lint:changelog --rc
      - name: Validate changelog
        if: ${{ !startsWith(github.head_ref, 'release/') }}
        run: yarn lint:changelog
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi

  test:
    name: Test
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install Corepack via Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install Yarn
        run: corepack enable
      - name: Install Node.js ${{ matrix.node-version }} and restore Yarn cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      # TODO: Remove --ignore-engines once devdeps compatible with node v20
      - name: Install dependencies via Yarn (ignoring engines)
        run: yarn --frozen-lockfile --ignore-engines
        if: "startsWith(matrix.node-version, '2')"
      - name: Install dependencies via Yarn
        run: yarn --frozen-lockfile
        if: "!startsWith(matrix.node-version, '2')"
      - run: yarn test
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi

  compatibility-test:
    name: Compatibility test
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install Corepack via Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install Yarn
        run: corepack enable
      - name: Install Node.js ${{ matrix.node-version }} and restore Yarn cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Remove yarn.lock
        run: rm yarn.lock
      # TODO: Remove --ignore-engines once devdeps compatible with node v20
      - name: Install dependencies via Yarn (ignoring engines)
        run: yarn --ignore-engines
        if: "startsWith(matrix.node-version, '2')"
      - name: Install dependencies via Yarn
        run: yarn
        if: "!startsWith(matrix.node-version, '2')"
      - run: yarn test
      - name: Restore lockfile
        run: git restore yarn.lock
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi
