name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn --frozen-lockfile --ignore-scripts
    - run: npx allow-scripts
    - run: yarn build
    - run: yarn lint
    - run: yarn test
  all-jobs-pass:
    name: All jobs pass
    runs-on: ubuntu-20.04
    needs:
      - build
    steps:
    - uses: actions/checkout@v2