# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    # do normal setup
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # get xvfb running for electron on ci
    - run: sudo apt-get install xvfb
    # run tests
    - run: yarn --frozen-lockfile
    - run: yarn run lint
    - run: yarn run build
    - run: xvfb-run --auto-servernum yarn testOnly
